spring:
  application: 
    name: HappickliveProduct
  profiles: 
    active: default
  datasource:
    #url: jdbc:h2:mem:testdb
    #username: sa
    #password:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: maria
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
 # h2:
 #  console:
 #     enabled: true
 #    path: /h2-console

server:
  port: 8080
       
logging:
  level:
    org.hibernate.SQL: debug
